FROM debian:stable

RUN rm /etc/apt/sources.list.d/debian.sources
COPY ./sources.list /etc/apt/sources.list

RUN apt update && apt install openssh-server -y
RUN mkdir /var/run/sshd/
RUN echo $RANDOM
RUN ssh-keygen -N {$RANDOM} -f /root/.ssh/id_rsa
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "root:debian12" | chpasswd
COPY authorized_keys /root/.ssh