version: '3.8'

services:
  TrainServer:
    image: imaiguo/debian:12
    container_name: Debian
    hostname: DockerDebianDev4C
    restart: always
    command: /usr/sbin/sshd -D
    # command: /sbin/init
    # command: /etc/init.d/xrdp start
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['0']
    #         capabilities: [gpu]
    ports:
      - "2021:22"
      - "2022:3389"
    volumes:
      - ./Data:/opt/Data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime     
      - ./sshkey:/home/ephraim/.ssh
      
